/*
 * This file is generated by jOOQ.
 */
package com.fbecloud.provider.db.identity.tables;


import com.fbecloud.provider.db.identity.Indexes;
import com.fbecloud.provider.db.identity.Keycloak;
import com.fbecloud.provider.db.identity.Keys;
import com.fbecloud.provider.db.identity.tables.records.UserEntityRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserEntity extends TableImpl<UserEntityRecord> {

    private static final long serialVersionUID = -1780741278;

    /**
     * The reference instance of <code>keycloak.USER_ENTITY</code>
     */
    public static final UserEntity USER_ENTITY = new UserEntity();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserEntityRecord> getRecordType() {
        return UserEntityRecord.class;
    }

    /**
     * The column <code>keycloak.USER_ENTITY.ID</code>.
     */
    public final TableField<UserEntityRecord, String> ID = createField("ID", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>keycloak.USER_ENTITY.EMAIL</code>.
     */
    public final TableField<UserEntityRecord, String> EMAIL = createField("EMAIL", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>keycloak.USER_ENTITY.EMAIL_CONSTRAINT</code>.
     */
    public final TableField<UserEntityRecord, String> EMAIL_CONSTRAINT = createField("EMAIL_CONSTRAINT", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>keycloak.USER_ENTITY.EMAIL_VERIFIED</code>.
     */
    public final TableField<UserEntityRecord, Boolean> EMAIL_VERIFIED = createField("EMAIL_VERIFIED", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "");

    /**
     * The column <code>keycloak.USER_ENTITY.ENABLED</code>.
     */
    public final TableField<UserEntityRecord, Boolean> ENABLED = createField("ENABLED", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "");

    /**
     * The column <code>keycloak.USER_ENTITY.FEDERATION_LINK</code>.
     */
    public final TableField<UserEntityRecord, String> FEDERATION_LINK = createField("FEDERATION_LINK", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>keycloak.USER_ENTITY.FIRST_NAME</code>.
     */
    public final TableField<UserEntityRecord, String> FIRST_NAME = createField("FIRST_NAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>keycloak.USER_ENTITY.LAST_NAME</code>.
     */
    public final TableField<UserEntityRecord, String> LAST_NAME = createField("LAST_NAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>keycloak.USER_ENTITY.REALM_ID</code>.
     */
    public final TableField<UserEntityRecord, String> REALM_ID = createField("REALM_ID", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>keycloak.USER_ENTITY.USERNAME</code>.
     */
    public final TableField<UserEntityRecord, String> USERNAME = createField("USERNAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>keycloak.USER_ENTITY.CREATED_TIMESTAMP</code>.
     */
    public final TableField<UserEntityRecord, Long> CREATED_TIMESTAMP = createField("CREATED_TIMESTAMP", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>keycloak.USER_ENTITY.SERVICE_ACCOUNT_CLIENT_LINK</code>.
     */
    public final TableField<UserEntityRecord, String> SERVICE_ACCOUNT_CLIENT_LINK = createField("SERVICE_ACCOUNT_CLIENT_LINK", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>keycloak.USER_ENTITY.NOT_BEFORE</code>.
     */
    public final TableField<UserEntityRecord, Integer> NOT_BEFORE = createField("NOT_BEFORE", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>keycloak.USER_ENTITY</code> table reference
     */
    public UserEntity() {
        this(DSL.name("USER_ENTITY"), null);
    }

    /**
     * Create an aliased <code>keycloak.USER_ENTITY</code> table reference
     */
    public UserEntity(String alias) {
        this(DSL.name(alias), USER_ENTITY);
    }

    /**
     * Create an aliased <code>keycloak.USER_ENTITY</code> table reference
     */
    public UserEntity(Name alias) {
        this(alias, USER_ENTITY);
    }

    private UserEntity(Name alias, Table<UserEntityRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserEntity(Name alias, Table<UserEntityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> UserEntity(Table<O> child, ForeignKey<O, UserEntityRecord> key) {
        super(child, key, USER_ENTITY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Keycloak.KEYCLOAK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USER_ENTITY_IDX_USER_EMAIL, Indexes.USER_ENTITY_PRIMARY, Indexes.USER_ENTITY_UK_DYKN684SL8UP1CRFEI6ECKHD7, Indexes.USER_ENTITY_UK_RU8TT6T700S9V50BU18WS5HA6);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserEntityRecord> getPrimaryKey() {
        return Keys.KEY_USER_ENTITY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserEntityRecord>> getKeys() {
        return Arrays.<UniqueKey<UserEntityRecord>>asList(Keys.KEY_USER_ENTITY_PRIMARY, Keys.KEY_USER_ENTITY_UK_DYKN684SL8UP1CRFEI6ECKHD7, Keys.KEY_USER_ENTITY_UK_RU8TT6T700S9V50BU18WS5HA6);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntity as(String alias) {
        return new UserEntity(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntity as(Name alias) {
        return new UserEntity(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserEntity rename(String name) {
        return new UserEntity(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserEntity rename(Name name) {
        return new UserEntity(name, null);
    }
}
