/*
 * This file is generated by jOOQ.
 */
package com.fbecloud.provider.db.identity;


import com.fbecloud.provider.db.identity.tables.UserEntity;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>keycloak</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USER_ENTITY_IDX_USER_EMAIL = Indexes0.USER_ENTITY_IDX_USER_EMAIL;
    public static final Index USER_ENTITY_PRIMARY = Indexes0.USER_ENTITY_PRIMARY;
    public static final Index USER_ENTITY_UK_DYKN684SL8UP1CRFEI6ECKHD7 = Indexes0.USER_ENTITY_UK_DYKN684SL8UP1CRFEI6ECKHD7;
    public static final Index USER_ENTITY_UK_RU8TT6T700S9V50BU18WS5HA6 = Indexes0.USER_ENTITY_UK_RU8TT6T700S9V50BU18WS5HA6;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USER_ENTITY_IDX_USER_EMAIL = Internal.createIndex("IDX_USER_EMAIL", UserEntity.USER_ENTITY, new OrderField[] { UserEntity.USER_ENTITY.EMAIL }, false);
        public static Index USER_ENTITY_PRIMARY = Internal.createIndex("PRIMARY", UserEntity.USER_ENTITY, new OrderField[] { UserEntity.USER_ENTITY.ID }, true);
        public static Index USER_ENTITY_UK_DYKN684SL8UP1CRFEI6ECKHD7 = Internal.createIndex("UK_DYKN684SL8UP1CRFEI6ECKHD7", UserEntity.USER_ENTITY, new OrderField[] { UserEntity.USER_ENTITY.REALM_ID, UserEntity.USER_ENTITY.EMAIL_CONSTRAINT }, true);
        public static Index USER_ENTITY_UK_RU8TT6T700S9V50BU18WS5HA6 = Internal.createIndex("UK_RU8TT6T700S9V50BU18WS5HA6", UserEntity.USER_ENTITY, new OrderField[] { UserEntity.USER_ENTITY.REALM_ID, UserEntity.USER_ENTITY.USERNAME }, true);
    }
}
