/*
 * This file is generated by jOOQ.
 */
package com.fbecloud.provider.db.identity;


import com.fbecloud.provider.db.identity.tables.UserEntity;
import com.fbecloud.provider.db.identity.tables.records.UserEntityRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>keycloak</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserEntityRecord> KEY_USER_ENTITY_PRIMARY = UniqueKeys0.KEY_USER_ENTITY_PRIMARY;
    public static final UniqueKey<UserEntityRecord> KEY_USER_ENTITY_UK_DYKN684SL8UP1CRFEI6ECKHD7 = UniqueKeys0.KEY_USER_ENTITY_UK_DYKN684SL8UP1CRFEI6ECKHD7;
    public static final UniqueKey<UserEntityRecord> KEY_USER_ENTITY_UK_RU8TT6T700S9V50BU18WS5HA6 = UniqueKeys0.KEY_USER_ENTITY_UK_RU8TT6T700S9V50BU18WS5HA6;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<UserEntityRecord> KEY_USER_ENTITY_PRIMARY = Internal.createUniqueKey(UserEntity.USER_ENTITY, "KEY_USER_ENTITY_PRIMARY", UserEntity.USER_ENTITY.ID);
        public static final UniqueKey<UserEntityRecord> KEY_USER_ENTITY_UK_DYKN684SL8UP1CRFEI6ECKHD7 = Internal.createUniqueKey(UserEntity.USER_ENTITY, "KEY_USER_ENTITY_UK_DYKN684SL8UP1CRFEI6ECKHD7", UserEntity.USER_ENTITY.REALM_ID, UserEntity.USER_ENTITY.EMAIL_CONSTRAINT);
        public static final UniqueKey<UserEntityRecord> KEY_USER_ENTITY_UK_RU8TT6T700S9V50BU18WS5HA6 = Internal.createUniqueKey(UserEntity.USER_ENTITY, "KEY_USER_ENTITY_UK_RU8TT6T700S9V50BU18WS5HA6", UserEntity.USER_ENTITY.REALM_ID, UserEntity.USER_ENTITY.USERNAME);
    }
}
