/*
 * This file is generated by jOOQ.
 */
package com.fbecloud.provider.db.identity;


import com.fbecloud.provider.db.identity.tables.UserEntity;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in keycloak
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>keycloak.USER_ENTITY</code>.
     */
    public static final UserEntity USER_ENTITY = com.fbecloud.provider.db.identity.tables.UserEntity.USER_ENTITY;
}
