server:
  port: 9000

spring:
  application:
    name: service-security

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8086/eureka
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 10

#actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG