/*
 * This file is generated by jOOQ.
 */
package com.fbecloud.provider.db.identity.tables.records;


import com.fbecloud.provider.db.identity.tables.UserEntity;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserEntityRecord extends UpdatableRecordImpl<UserEntityRecord> implements Record13<String, String, String, Boolean, Boolean, String, String, String, String, String, Long, String, Integer> {

    private static final long serialVersionUID = 1520159428;

    /**
     * Setter for <code>keycloak.USER_ENTITY.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>keycloak.USER_ENTITY.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>keycloak.USER_ENTITY.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>keycloak.USER_ENTITY.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>keycloak.USER_ENTITY.EMAIL_CONSTRAINT</code>.
     */
    public void setEmailConstraint(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>keycloak.USER_ENTITY.EMAIL_CONSTRAINT</code>.
     */
    public String getEmailConstraint() {
        return (String) get(2);
    }

    /**
     * Setter for <code>keycloak.USER_ENTITY.EMAIL_VERIFIED</code>.
     */
    public void setEmailVerified(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>keycloak.USER_ENTITY.EMAIL_VERIFIED</code>.
     */
    public Boolean getEmailVerified() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>keycloak.USER_ENTITY.ENABLED</code>.
     */
    public void setEnabled(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>keycloak.USER_ENTITY.ENABLED</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>keycloak.USER_ENTITY.FEDERATION_LINK</code>.
     */
    public void setFederationLink(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>keycloak.USER_ENTITY.FEDERATION_LINK</code>.
     */
    public String getFederationLink() {
        return (String) get(5);
    }

    /**
     * Setter for <code>keycloak.USER_ENTITY.FIRST_NAME</code>.
     */
    public void setFirstName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>keycloak.USER_ENTITY.FIRST_NAME</code>.
     */
    public String getFirstName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>keycloak.USER_ENTITY.LAST_NAME</code>.
     */
    public void setLastName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>keycloak.USER_ENTITY.LAST_NAME</code>.
     */
    public String getLastName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>keycloak.USER_ENTITY.REALM_ID</code>.
     */
    public void setRealmId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>keycloak.USER_ENTITY.REALM_ID</code>.
     */
    public String getRealmId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>keycloak.USER_ENTITY.USERNAME</code>.
     */
    public void setUsername(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>keycloak.USER_ENTITY.USERNAME</code>.
     */
    public String getUsername() {
        return (String) get(9);
    }

    /**
     * Setter for <code>keycloak.USER_ENTITY.CREATED_TIMESTAMP</code>.
     */
    public void setCreatedTimestamp(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>keycloak.USER_ENTITY.CREATED_TIMESTAMP</code>.
     */
    public Long getCreatedTimestamp() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>keycloak.USER_ENTITY.SERVICE_ACCOUNT_CLIENT_LINK</code>.
     */
    public void setServiceAccountClientLink(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>keycloak.USER_ENTITY.SERVICE_ACCOUNT_CLIENT_LINK</code>.
     */
    public String getServiceAccountClientLink() {
        return (String) get(11);
    }

    /**
     * Setter for <code>keycloak.USER_ENTITY.NOT_BEFORE</code>.
     */
    public void setNotBefore(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>keycloak.USER_ENTITY.NOT_BEFORE</code>.
     */
    public Integer getNotBefore() {
        return (Integer) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, Boolean, Boolean, String, String, String, String, String, Long, String, Integer> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, Boolean, Boolean, String, String, String, String, String, Long, String, Integer> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return UserEntity.USER_ENTITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserEntity.USER_ENTITY.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserEntity.USER_ENTITY.EMAIL_CONSTRAINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return UserEntity.USER_ENTITY.EMAIL_VERIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return UserEntity.USER_ENTITY.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return UserEntity.USER_ENTITY.FEDERATION_LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return UserEntity.USER_ENTITY.FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return UserEntity.USER_ENTITY.LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return UserEntity.USER_ENTITY.REALM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return UserEntity.USER_ENTITY.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return UserEntity.USER_ENTITY.CREATED_TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return UserEntity.USER_ENTITY.SERVICE_ACCOUNT_CLIENT_LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return UserEntity.USER_ENTITY.NOT_BEFORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEmailConstraint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getEmailVerified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getFederationLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getRealmId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component11() {
        return getCreatedTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getServiceAccountClientLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getNotBefore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmailConstraint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getEmailVerified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFederationLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getRealmId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getCreatedTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getServiceAccountClientLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getNotBefore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value2(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value3(String value) {
        setEmailConstraint(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value4(Boolean value) {
        setEmailVerified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value5(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value6(String value) {
        setFederationLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value7(String value) {
        setFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value8(String value) {
        setLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value9(String value) {
        setRealmId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value10(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value11(Long value) {
        setCreatedTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value12(String value) {
        setServiceAccountClientLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord value13(Integer value) {
        setNotBefore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserEntityRecord values(String value1, String value2, String value3, Boolean value4, Boolean value5, String value6, String value7, String value8, String value9, String value10, Long value11, String value12, Integer value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserEntityRecord
     */
    public UserEntityRecord() {
        super(UserEntity.USER_ENTITY);
    }

    /**
     * Create a detached, initialised UserEntityRecord
     */
    public UserEntityRecord(String id, String email, String emailConstraint, Boolean emailVerified, Boolean enabled, String federationLink, String firstName, String lastName, String realmId, String username, Long createdTimestamp, String serviceAccountClientLink, Integer notBefore) {
        super(UserEntity.USER_ENTITY);

        set(0, id);
        set(1, email);
        set(2, emailConstraint);
        set(3, emailVerified);
        set(4, enabled);
        set(5, federationLink);
        set(6, firstName);
        set(7, lastName);
        set(8, realmId);
        set(9, username);
        set(10, createdTimestamp);
        set(11, serviceAccountClientLink);
        set(12, notBefore);
    }
}
